
# Global options
baseURL = "https://www.julian-thomas-thomas.de"
relativeURLs = true
canonifyURLs = true
copyright = "© 2025 by Julian Thomas Thomas. <a href='/imprint'>Imprint</a>."
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
languageCode = "en"
theme = "barks"
title = "Julian Thomas"



# Main menu
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 2
[[menu.main]]
    name = "Publications"
    url  = "/publications"
    weight = 2
[[menu.main]]
    name = "Talks"
    url  = "/talks"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url  = "/teaching"
    weight = 2

[[menu.main]]
    name = "CV"
    url  = "/cv"
    weight = 3

# Customization options
[params]

    [params.head]
        author = "Julian Thomas"
        custom_css = "/custom.css"
        description = "Hi, I'm Julian"
        keywords = ["cryptography", "security", "FAU"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
#        title_font = "Urbanist"
        title_font = "Cutive Mono"
        body_font = "Source Sans Pro"

    [params.colors]
        theme_color = "#333333"
        background_color = "#fcfbf9"
        text_color = "#333333"
        link_color = "#800080"


    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/3Komma1415"
        weight = 2
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square"
        url = "https://scholar.google.com/citations?user=qCPdTnoAAAAJ&hl=de&authuser=2"
        weight = 3
    [params.social.institution]
        name = "My institution"
        class = "fas fa-university"
        url = "https://www.chaac.tf.fau.de"
        weight = 5



# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'

