################################# Default configuration ###################
baseURL = "https://www.paul-gerhart.de"
title = "Paul Gerhart"
theme = "PGTheme"
# disable language
disableLanguages = []
timeout = "10m"
disableKinds = ['rss']

################### English Navigation ########################

[[Languages.en.menu.main]]
name = "CV"
url = "/cv"
weight = 1

[[Languages.en.menu.main]]
name = "Publications"
url = "/publications"
weight = 2

[[Languages.en.menu.main]]
name = "Talks"
url = "/talks"
weight = 3


[[Languages.en.menu.main]]
name = "Imprint"
url = "imprint"
weight = 11

############################# Default Parameters ##########################
[params]
logo = "images/PGLogoHighContrast.svg"
portrait = "images/portrait.jpg"
author = "Paul Gerhart"
title = "Paul Gerhart"
ustid = ""

[mediaTypes]
[mediaTypes."application/x-tex"]
suffixes = ["tex"]

[outputFormats]
[outputFormats.TEX]
mediaType = "application/x-tex"
baseName = "index"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "TEX"]


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
copyright = "Copyright &copy; 2024 Paul Gerhart"
