################################# Default configuration ###################
baseURL = "https://3komma1415.github.io/jttwebpage/"
title = "Julian Thomas Thomas"
theme = "PGTheme"
# disable language
disableLanguages = []
timeout = "10m"
disableKinds = ['rss']

################### English Navigation ########################

[[Languages.en.menu.main]]
name = "CV"
url = "/cv"
weight = 1

[[Languages.en.menu.main]]
name = "Publications"
url = "/publications"
weight = 2

[[Languages.en.menu.main]]
name = "Talks"
url = "/talks"
weight = 3


[[Languages.en.menu.main]]
name = "Imprint"
url = "imprint"
weight = 11

############################# Default Parameters ##########################
[params]
logo = "images/jttlogo.pdf"
portrait = "images/portrait.jpg"
author = "Julian Thomas Thomas"
title = "Julian Thomas Thomas"
ustid = ""

[mediaTypes]
[mediaTypes."application/x-tex"]
suffixes = ["tex"]

[outputFormats]
[outputFormats.TEX]
mediaType = "application/x-tex"
baseName = "index"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "TEX"]


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
copyright = "Copyright &copy; 2025 Julian Thomas Thomas"
